spring:
  cloud:
    config:
      override-system-properties: false
  config:
    customer-url: http://localhost:8080/api/customers
    products-url: http://localhost:8080/api/products
    payments-url: http://localhost:8080/api/payments        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
