spring:
  cloud:
    config:
      override-system-properties: false        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
application:
  config:
    customer-url: http://localhost:8080/api/customers
    product-url: http://localhost:8080/api/products
    payment-url: http://localhost:8080/api/payments
