spring:
    data:
        mongodb:
          uri: mongodb://root:secret@localhost:27017/product-service?authSource=admin
        jpa:
          show-sql: true
server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
